# Generated by Django 3.0.3 on 2020-03-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
